#!/usr/bin/env python3

import argparse
import csv

# 90 degrees clock wise = 270
# 90 degrees counter clock wise = 90

mappings = {
    "LQFP-48": 270,
    "PinHeader": 90,
    "QFN-28": 270,
    "QFN-48": 270,
    "QFN-64": 270,
    "SOIC-16": 270,
    "SOIC-8": 270,
    "SOT-223": 180,
    "SOT-363": 180,
    "SOT-23": 180,
    "SOT-23-5": 90,
    "SOT-23W": 90,
    "SOT-666": 270,
    "VQFN-24": 270,
    "VSSOP-8": 180,
    "Sensirion_DFN-4": 270,
}

if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="Fix Rotation", description="Fixes rotation in position file for JLCPCB")
    parser.add_argument("-i", "--infile", required=True)
    parser.add_argument("-o", "--outfile", required=True)
    args = parser.parse_args()
    with open(args.infile) as infile:
        with open(args.outfile, "w+") as outfile:
            reader = csv.DictReader(infile)
            writer = csv.DictWriter(outfile, fieldnames=reader.fieldnames, quoting=csv.QUOTE_ALL)
            writer.writeheader()
            for row in reader:
                row["Rotation"] = float(row["Rotation"])
                for key, value in mappings.items():
                    if row["Package"].startswith(key):
                        row["Rotation"] = value + row["Rotation"]
                writer.writerow(row)
